### PR TITLE
added wiki service to the fabulous bot

### PR DESCRIPTION
**Pull request by LordSomen**
It is working , Current now it only shows the url but I can easily add more features to it. Yeah I parsed the MediaWiki api.
Hope It will Works.
thank you,
Let me know if any changes or if any error occurs.

### CODE REVIEW

**Comment by vicky002** [comment]
That's a lot of changes and commits. 
I will have to see your code in-depth before I merge to master. 

Give me some time.

@bikrambhattacharya @nitish1995 you guys can review this code.

**Comment by LordSomen** [comment]
I just added some extra code for future development , If you want I can shrink the lines of code so that you can easily see the code in depth.Let me know ....

**Comment by bikrambhattacharya** [comment]
@vicky002 Service not working properly due to some import error.
image

**Comment by LordSomen** [comment]
image
I have no idea bro how this error was created , You can look at the image file , maybe you accidentally removed the import command , because in my computer no error is showing .
Yes another thing I have no idea why for facebook my code can't find anything I think mediawiki api blocking it , ask Mark Zuckerberg !! LOL !! 
because  after you mentioned this problem I tried with many others names but for them it is giving the corrrect url.
image

but for facebook I think I have to add a exception . 
the best you can see about my code is even though user is not giving accurate input my wiki service is giving the the related result if they can found.  
hope this will help!!
Thank you!!

**Comment by vicky002** [comment]
This is related to your code only. Check your code have you created `Wikipedia` module? There should be `__init__.py` file or see if you have given the path of your module properly.

**Comment by LordSomen** [comment]
Okk, but I need time , now I am busy it is not possible for 0.1.1 release!!! ,
If you want everything perfect!!
I will try hard.
Thank You.

**Comment by vicky002** [comment]
no response yet, so closing this one.

**Pull request closed without merging**
