### PR TITLE
Added Google Search Service using Custom Search API

### PR DESCRIPTION
**Pull request by anshulnsit**
I have added the google service functionality

### CODE REVIEW

**Comment by bikrambhattacharya** [comment]
@anshulnsit  Is it working properly?

**Comment by anshulnsit** [comment]
@bikrambhattacharya Yes , It is working on my local machine. You can test it

**Comment by bikrambhattacharya** [comment]
okay wait @anshulnsit

**Comment by anshulnsit** [comment]
@bikrambhattacharya 
fabulous

**Comment by anshulnsit** [comment]
@bikrambhattacharya Can you post the error you are getting?

**Comment by bikrambhattacharya** [comment]
@anshulnsit 
image

**Comment by anshulnsit** [comment]
@bikrambhattacharya Did you update requirements.txt file?

**Comment by bikrambhattacharya** [comment]
@anshulnsit NO

**Comment by anshulnsit** [comment]
@bikrambhattacharya You need google api client library to use the API. I have added it in requirements.txt. Please update it and then test it

**Comment by bikrambhattacharya** [comment]
@anshulnsit  I cloned your repo then testing @vicky002  please check may be this is error due to different python version

**Comment by bikrambhattacharya** [comment]
@anshulnsit  probably i faced error due to different python version

**Comment by anshulnsit** [comment]
@bikrambhattacharya were you able to run it successfully after changing python version?

**Comment by vicky002** [comment]
@anshulnsit there is a conflict, please resolve.

**Comment by anshulnsit** [comment]
@vicky002 Resolved Conficts

**Pull request merged**
