### PR TITLE
Added google search service

### PR DESCRIPTION
**Pull request by anshulnsit**
I have added google search service.
Can be used by typing ~google query

### CODE REVIEW

**Comment by vicky002** [comment]
Hey @anshulnsit , can we show two results in the response? 

As people generally, read at least first three results. I think we should show two.

**Comment by anshulnsit** [comment]
@vicky002 yes you are correct. Will update the code. 
@vicky002 currently i use beautifulsoup to scrape the data but that is slow. Is there another way of doing fast search.

**Comment by vicky002** [comment]
@anshulnsit you can use Google Search API : https://developers.google.com/custom-search/?csw=1 

This has some limitations though - 100 calls/per day, but it's enough for an organization, as seen if needs to do lot more than just a normal search, he will have to open browser and search. 

To get results right inside Slack, 100 calls/day is good enough.

**Comment by vicky002** [comment]
@anshulnsit 👆 There are conflicts.

**Comment by anshulnsit** [comment]
@vicky002 you already merged the PR to add the service. No need to merge this PR

**Comment by vicky002** [comment]
closing it then.

**Pull request closed without merging**
